version: '3'

tasks:
  default:
    cmds:
      - task dactyl:build
  dactyl:build:
    cmds:
      - util/docker_build_update.sh handwired/dactyl_manuform/5x6:seanflannery10

  sofle:build:
    cmds:
      - util/docker_build_update.sh sofle:seanflannery10
