version: '3'

tasks:
  default:
    cmds:
      - task dactyl:build
  dactyl:build:
    cmds:
      - qmk build -kb mangokb/dactyl -km default

  dactyl:flash:
    cmds:
      - qmk flash -kb mangokb/dactyl -km default

  sofle:build:
    cmds:
      - util/docker_build_update.sh sofle:seanflannery10
