version: '3'

tasks:
  default:
    cmds:
      - task dactyl:build
  dactyl:compile:
    cmds:
      - qmk compile -kb mangokb/dactyl -km seanflannery10

  dactyl:flash:
    cmds:
      - qmk flash -kb mangokb/dactyl -km seanflannery10

  sofle:build:
    cmds:
      - util/docker_build_update.sh sofle:seanflannery10
